### ISSUE TITLE
.NET build check failed

### ISSUE THREAD

**Issue by Johannes704** [ITU-BDSA2026-GROUP19/Bison#15]
Check after merging DBsingleton branch to main has failed

**Comment by Johannes704** [comment]
Run dotnet build Bison.CLI/Bison.CLI.csproj --no-restore
  SimpleDB -> /home/runner/work/Bison/Bison/SimpleDB/bin/Debug/net8.0/SimpleDB.dll
Error: /home/runner/work/Bison/Bison/Bison.CLI/Program.cs(7,53): error CS1729: 'CSVDatabase<Observation>' does not contain a constructor that takes 1 arguments [/home/runner/work/Bison/Bison/Bison.CLI/Bison.CLI.csproj]
Error: /home/runner/work/Bison/Bison/Bison.CLI/Program.cs(9,45): error CS1729: 'CSVDatabase<Comment>' does not contain a constructor that takes 1 arguments [/home/runner/work/Bison/Bison/Bison.CLI/Bison.CLI.csproj]

Build FAILED.

Error: /home/runner/work/Bison/Bison/Bison.CLI/Program.cs(7,53): error CS1729: 'CSVDatabase<Observation>' does not contain a constructor that takes 1 arguments [/home/runner/work/Bison/Bison/Bison.CLI/Bison.CLI.csproj]
Error: /home/runner/work/Bison/Bison/Bison.CLI/Program.cs(9,45): error CS1729: 'CSVDatabase<Comment>' does not contain a constructor that takes 1 arguments [/home/runner/work/Bison/Bison/Bison.CLI/Bison.CLI.csproj]
    0 Warning(s)
    2 Error(s)

Time Elapsed 00:00:04.72
Error: Process completed with exit code 1.
